### ISSUE TITLE
Building Instructions clarification

### ISSUE THREAD

**Issue by FilBot3** [rathann/vmware-horizon-client#1]
# Description

I am wanting to use this repository to build an RPM for VMware Horizon Client specifically for Fedora Silverblue and Fedora Kinoite. Since these are rpm-ostree distributions, the `.bundle` install that VMWare provides doesn't work.

I have found that I need to install

```bash
sudo dnf install fedpkg
```

or for Silverblue/Kinoit

```bash
sudo rpm-ostree install fedpkg
```

I even installed it in the `toolbx` instance.

However, when I run `fedpkg srpm`, I get the following error

```bash
[dudleyp@fedora vmware-horizon-client]$ fedpkg srpm
sources file doesn't exist. Source files download skipped.
Could not execute srpm: Could not find the release/dist from branch name master
Please specify with --release
```

What should be done here to make this build?

**Comment by FilBot3** [comment]
I did try to run the provided shell script first, then run the `fedpkg srpm` same result. Then reading through

* https://docs.fedoraproject.org/en-US/package-maintainers/Package_Maintenance_Guide/

Didn't seem to yield much difference. I think I may be missing something.

**Comment by ianskoo** [comment]
I'm having the same problem with the `fedpkg srpm` command. @FilBot3 have you found something out?

**Comment by dutchthomas** [comment]
Here's an example on Fedora 35, but other releases or epel should work too

(as root... or add yourself to the right groups first and/or use sudo)

# install rpmfusion-free first
dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm

# Install deps
dnf install fedpkg mock mock-rpmfusion-free

# Get these sources
git clone https://gitlab.com/greysector/rpms/vmware-horizon-client.git
cd vmware-horizon-client

# Download  upstream vmware sources
spectool -g vmware-horizon-client.spec

# Make source package
fedpkg --release f35 srpm

# Build binary packages
mock -r fedora-35-x86_64-rpmfusion_free vmware-horizon-client-2111.8.4.0.18957622-1.fc35.src.rpm

# Install binary packages (exclude source packages)
ls /var/lib/mock/fedora-35-x86_64/result/vmware-horizon-client-* | grep -v '.src.' | xargs dnf install -y

**Comment by FilBot3** [comment]
There's also a Flatpak project in the works: https://github.com/FilBot3/com.vmware.HorizonClient
